/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import okhttp3.*;

import javax.swing.*;
import java.awt.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class App {
    private JFrame frame;
    private JPanel chatPanel;
    private JTextField inputField;
    private JScrollPane scrollPane;
    private List<JsonObject> messageHistory;
    private final String apiKey = "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";

    public App() {
        messageHistory = new ArrayList<>();
        setupUI();
    }

    private void setupUI() {
        // 设置主窗口
        frame = new JFrame("Chat UI");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(400, 600);
        frame.setLayout(new BorderLayout());

        // 聊天内容面板
        chatPanel = new JPanel();
        chatPanel.setLayout(new BoxLayout(chatPanel, BoxLayout.Y_AXIS));
        chatPanel.setBackground(Color.WHITE);

        // 设置滚动条
        scrollPane = new JScrollPane(chatPanel);
        scrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16); // 增强滚动速度

        // 设置输入框
        inputField = new JTextField();
        inputField.setFont(new Font("SansSerif", Font.PLAIN, 14));
        inputField.addActionListener(e -> {
            String userInput = inputField.getText();
            inputField.setText("");
            processUserInput(userInput);
        });

        // 添加组件到窗口
        frame.add(scrollPane, BorderLayout.CENTER);
        frame.add(inputField, BorderLayout.SOUTH);

        frame.setVisible(true);
    }

    private void processUserInput(String userInput) {
        if (!userInput.trim().isEmpty()) {
            // 显示用户的聊天气泡
            addMessageBubble(userInput, true);

            // 将用户输入封装为 JsonObject 并添加到历史记录
            JsonObject userMessage = new JsonObject();
            userMessage.addProperty("role", "user");
            userMessage.addProperty("content", userInput);
            messageHistory.add(userMessage);

            try {
                String response = getChatResponse();

                // 显示系统的聊天气泡
                addMessageBubble(response, false);

                // 将系统回复封装为 JsonObject 并添加到历史记录
                JsonObject assistantMessage = new JsonObject();
                assistantMessage.addProperty("role", "assistant");
                assistantMessage.addProperty("content", response);
                messageHistory.add(assistantMessage);

                // 自动滚动到底部
                chatPanel.revalidate();
                SwingUtilities.invokeLater(() -> scrollPane.getVerticalScrollBar().setValue(scrollPane.getVerticalScrollBar().getMaximum()));
            } catch (IOException | InterruptedException e) {
                e.printStackTrace();
                addMessageBubble("Error: Unable to get response from OpenAI.", false);
            }
        }
    }

    private String getChatResponse() throws IOException, InterruptedException {
        OkHttpClient client = new OkHttpClient();
        Gson gson = new Gson();

        // 构建请求体
        JsonObject requestBody = new JsonObject();
        requestBody.addProperty("model", "gpt-3.5-turbo");

        // 使用 messageHistory 作为消息历史
        JsonArray messages = new JsonArray();
        for (JsonObject message : messageHistory) {
            messages.add(message);
        }
        requestBody.add("messages", messages);

        // 创建请求
        Request request = new Request.Builder()
                .url("https://api.openai.com/v1/chat/completions")
                .post(RequestBody.create(requestBody.toString(), MediaType.parse("application/json")))
                .addHeader("Authorization", "Bearer " + apiKey)
                .build();

        try (Response response = client.newCall(request).execute()) {
            if (response.code() == 429) {
                System.out.println("Rate limit exceeded. Waiting and retrying...");
                Thread.sleep(5000);  // 等待 5 秒后重试
                return getChatResponse();  // 递归调用，重试请求
            }
            if (!response.isSuccessful()) throw new IOException("Unexpected code " + response);

            JsonObject jsonResponse = gson.fromJson(response.body().string(), JsonObject.class);
            return jsonResponse.getAsJsonArray("choices").get(0)
                    .getAsJsonObject().get("message")
                    .getAsJsonObject().get("content").getAsString();
        }
    }

    private void addMessageBubble(String message, boolean isUser) {
        JPanel messageBubble = new JPanel();
        messageBubble.setLayout(new BorderLayout());
        messageBubble.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));

        JTextArea messageText = new JTextArea(message);
        messageText.setWrapStyleWord(true);
        messageText.setLineWrap(true);
        messageText.setEditable(false);
        messageText.setFont(new Font("SansSerif", Font.PLAIN, 14));
        messageText.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        messageText.setMaximumSize(new Dimension(250, Integer.MAX_VALUE));  // 限制气泡的最大宽度

        // 设置气泡颜色和对齐方式
        if (isUser) {
            messageText.setBackground(new Color(173, 216, 230)); // 浅蓝色
            messageBubble.add(messageText, BorderLayout.EAST);
        } else {
            messageText.setBackground(new Color(240, 240, 240)); // 浅灰色
            messageBubble.add(messageText, BorderLayout.WEST);
        }
        messageText.setForeground(Color.BLACK);

        chatPanel.add(messageBubble);
        chatPanel.revalidate();
    }

    public static void main(String[] args) {
        new App();
    }
}

